# Don't run it from Visual Studio, Telemetry won't see the request

POST https://localhost:7210/api/hello?page=api&line=auto
Content-Type: application/json

{
  "name": "Peter",
  "age": 20
}

###

POST https://localhost:7210/api/hello-failed?page=api&line=auto
Content-Type: application/json

{
  "name": "Peter",
  "age": 20
}